name: C/C++ CI

on:
  push:
    branches: [ darky ]
  pull_request:
    branches: [ darky ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
